-- P0 cross-cutting security sweep. Revoke anon and PUBLIC EXECUTE on every
-- callable SECURITY DEFINER RPC in the public schema. Wrapped in a single DO
-- block executed as dynamic SQL because the Supabase CLI statement splitter
-- (v2.78.1) mis-tokenizes long runs of REVOKE/GRANT and raises 42601; one
-- dollar-quoted statement sidesteps it. Companion file 20260601120100 adds the
-- two function body guards. Full rationale and probe results in the PR body.
DO $do$
BEGIN
  EXECUTE 'REVOKE ALL ON FUNCTION public.decrypt_phi_boolean(encrypted_text text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.decrypt_phi_boolean(encrypted_text text) FROM anon';
  EXECUTE 'REVOKE ALL ON FUNCTION public.decrypt_phi_boolean(encrypted_text text) FROM authenticated';
  EXECUTE 'REVOKE ALL ON FUNCTION public.decrypt_phi_date(encrypted_text text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.decrypt_phi_date(encrypted_text text) FROM anon';
  EXECUTE 'REVOKE ALL ON FUNCTION public.decrypt_phi_date(encrypted_text text) FROM authenticated';
  EXECUTE 'REVOKE ALL ON FUNCTION public.decrypt_phi_text(encrypted_text text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.decrypt_phi_text(encrypted_text text) FROM anon';
  EXECUTE 'REVOKE ALL ON FUNCTION public.decrypt_phi_text(encrypted_text text) FROM authenticated';
  EXECUTE 'REVOKE ALL ON FUNCTION public.decrypt_phi_text_logged(encrypted_text text, p_actor_user_id uuid, p_target_user_id uuid, p_field_name text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.decrypt_phi_text_logged(encrypted_text text, p_actor_user_id uuid, p_target_user_id uuid, p_field_name text) FROM anon';
  EXECUTE 'REVOKE ALL ON FUNCTION public.decrypt_phi_text_logged(encrypted_text text, p_actor_user_id uuid, p_target_user_id uuid, p_field_name text) FROM authenticated';
  EXECUTE 'REVOKE ALL ON FUNCTION public.encrypt_phi_boolean(bool_value boolean) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.encrypt_phi_boolean(bool_value boolean) FROM anon';
  EXECUTE 'REVOKE ALL ON FUNCTION public.encrypt_phi_boolean(bool_value boolean) FROM authenticated';
  EXECUTE 'REVOKE ALL ON FUNCTION public.encrypt_phi_date(date_value date) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.encrypt_phi_date(date_value date) FROM anon';
  EXECUTE 'REVOKE ALL ON FUNCTION public.encrypt_phi_date(date_value date) FROM authenticated';
  EXECUTE 'REVOKE ALL ON FUNCTION public.encrypt_phi_text(plain_text text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.encrypt_phi_text(plain_text text) FROM anon';
  EXECUTE 'REVOKE ALL ON FUNCTION public.encrypt_phi_text(plain_text text) FROM authenticated';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_phi_encryption_key() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_phi_encryption_key() FROM anon';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_phi_encryption_key() FROM authenticated';
  EXECUTE 'REVOKE ALL ON FUNCTION public.assign_coach_atomic(p_user_id uuid, p_service_id uuid, p_focus_areas text[], p_requested_coach_id uuid, p_is_team_plan boolean, p_selected_team_id uuid, p_session_booking_enabled boolean, p_weekly_session_limit integer, p_session_duration_minutes integer) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.assign_coach_atomic(p_user_id uuid, p_service_id uuid, p_focus_areas text[], p_requested_coach_id uuid, p_is_team_plan boolean, p_selected_team_id uuid, p_session_booking_enabled boolean, p_weekly_session_limit integer, p_session_duration_minutes integer) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.assign_coach_atomic(p_user_id uuid, p_service_id uuid, p_focus_areas text[], p_requested_coach_id uuid, p_is_team_plan boolean, p_selected_team_id uuid, p_session_booking_enabled boolean, p_weekly_session_limit integer, p_session_duration_minutes integer) TO service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.book_session_atomic(p_slot_id uuid, p_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.book_session_atomic(p_slot_id uuid, p_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.book_session_atomic(p_slot_id uuid, p_user_id uuid) TO service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.coach_assignment_would_block(p_coach_user_id uuid, p_service_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.coach_assignment_would_block(p_coach_user_id uuid, p_service_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.coach_assignment_would_block(p_coach_user_id uuid, p_service_id uuid) TO service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.process_care_team_discharges() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.process_care_team_discharges() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.process_care_team_discharges() TO service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.purchase_addon_atomic(p_client_id uuid, p_addon_service_id uuid, p_payment_id uuid, p_quantity integer, p_discount_percent numeric) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.purchase_addon_atomic(p_client_id uuid, p_addon_service_id uuid, p_payment_id uuid, p_quantity integer, p_discount_percent numeric) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.purchase_addon_atomic(p_client_id uuid, p_addon_service_id uuid, p_payment_id uuid, p_quantity integer, p_discount_percent numeric) TO service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.admin_get_coaches_directory() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.admin_get_coaches_directory() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_coaches_directory() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.admin_get_coaches_full() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.admin_get_coaches_full() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_coaches_full() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.admin_get_profile_private(p_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.admin_get_profile_private(p_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_profile_private(p_user_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.assign_macrocycle_to_client(p_coach_id uuid, p_client_id uuid, p_subscription_id uuid, p_macrocycle_id uuid, p_start_date date, p_team_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.assign_macrocycle_to_client(p_coach_id uuid, p_client_id uuid, p_subscription_id uuid, p_macrocycle_id uuid, p_start_date date, p_team_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.assign_macrocycle_to_client(p_coach_id uuid, p_client_id uuid, p_subscription_id uuid, p_macrocycle_id uuid, p_start_date date, p_team_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.assign_program_to_client(p_coach_id uuid, p_client_id uuid, p_subscription_id uuid, p_template_id uuid, p_start_date date, p_team_id uuid, p_macrocycle_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.assign_program_to_client(p_coach_id uuid, p_client_id uuid, p_subscription_id uuid, p_template_id uuid, p_start_date date, p_team_id uuid, p_macrocycle_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.assign_program_to_client(p_coach_id uuid, p_client_id uuid, p_subscription_id uuid, p_template_id uuid, p_start_date date, p_team_id uuid, p_macrocycle_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.bootstrap_admin(admin_email text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.bootstrap_admin(admin_email text) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.bootstrap_admin(admin_email text) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.calculate_addon_session_payout(p_addon_service_id uuid, p_professional_level professional_level) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.calculate_addon_session_payout(p_addon_service_id uuid, p_professional_level professional_level) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.calculate_addon_session_payout(p_addon_service_id uuid, p_professional_level professional_level) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.calculate_subscription_payout(p_subscription_id uuid, p_discount_percentage numeric) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.calculate_subscription_payout(p_subscription_id uuid, p_discount_percentage numeric) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.calculate_subscription_payout(p_subscription_id uuid, p_discount_percentage numeric) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.can_assign_workouts(p_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.can_assign_workouts(p_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.can_assign_workouts(p_user_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.can_manage_care_team(p_user_id uuid, p_subscription_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.can_manage_care_team(p_user_id uuid, p_subscription_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.can_manage_care_team(p_user_id uuid, p_subscription_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.can_write_injury_notes(p_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.can_write_injury_notes(p_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.can_write_injury_notes(p_user_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.can_write_psych_notes(p_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.can_write_psych_notes(p_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.can_write_psych_notes(p_user_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.check_failed_payments() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.check_failed_payments() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.check_failed_payments() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.check_legacy_table_security() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.check_legacy_table_security() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.check_legacy_table_security() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.check_training_completion(p_coach_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.check_training_completion(p_coach_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.check_training_completion(p_coach_user_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.cleanup_expired_discount_applications() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.cleanup_expired_discount_applications() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.cleanup_expired_discount_applications() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.client_has_dietitian(p_client_uid uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.client_has_dietitian(p_client_uid uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.client_has_dietitian(p_client_uid uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.convert_muscle_plan_to_program(p_coach_id uuid, p_plan_name text, p_plan_description text, p_muscle_template_id uuid, p_day_slots jsonb) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.convert_muscle_plan_to_program(p_coach_id uuid, p_plan_name text, p_plan_description text, p_muscle_template_id uuid, p_day_slots jsonb) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.convert_muscle_plan_to_program(p_coach_id uuid, p_plan_name text, p_plan_description text, p_muscle_template_id uuid, p_day_slots jsonb) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.convert_muscle_plan_to_program_v2(p_coach_id uuid, p_plan_name text, p_plan_description text, p_muscle_template_id uuid, p_sessions jsonb) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.convert_muscle_plan_to_program_v2(p_coach_id uuid, p_plan_name text, p_plan_description text, p_muscle_template_id uuid, p_sessions jsonb) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.convert_muscle_plan_to_program_v2(p_coach_id uuid, p_plan_name text, p_plan_description text, p_muscle_template_id uuid, p_sessions jsonb) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.discharge_care_team_member(p_assignment_id uuid, p_reason_code care_team_end_reason, p_notes text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.discharge_care_team_member(p_assignment_id uuid, p_reason_code care_team_end_reason, p_notes text) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.discharge_care_team_member(p_assignment_id uuid, p_reason_code care_team_end_reason, p_notes text) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_active_care_team_for_date(p_subscription_id uuid, p_day_date date) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_active_care_team_for_date(p_subscription_id uuid, p_day_date date) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_active_care_team_for_date(p_subscription_id uuid, p_day_date date) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_admin_analytics() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_admin_analytics() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_admin_analytics() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_client_age(p_client_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_client_age(p_client_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_client_age(p_client_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_client_from_program(p_program_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_client_from_program(p_program_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_client_from_program(p_program_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_client_gender(p_client_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_client_gender(p_client_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_client_gender(p_client_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_client_height_cm(p_client_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_client_height_cm(p_client_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_client_height_cm(p_client_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_client_medical_flags(p_client_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_client_medical_flags(p_client_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_client_medical_flags(p_client_user_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_coach_analytics(coach_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_coach_analytics(coach_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_coach_analytics(coach_user_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_coach_assignment_progress() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_coach_assignment_progress() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_coach_assignment_progress() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_coach_client_tenure(p_coach_uid uuid, p_client_uid uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_coach_client_tenure(p_coach_uid uuid, p_client_uid uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_coach_client_tenure(p_coach_uid uuid, p_client_uid uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_coach_for_client(p_coach_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_coach_for_client(p_coach_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_coach_for_client(p_coach_user_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_coaches_for_subscription_addons(p_subscription_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_coaches_for_subscription_addons(p_subscription_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_coaches_for_subscription_addons(p_subscription_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_current_week_bounds() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_current_week_bounds() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_current_week_bounds() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_decrypted_form_submission(submission_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_decrypted_form_submission(submission_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_decrypted_form_submission(submission_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_default_admin_coach_user_id() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_default_admin_coach_user_id() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_default_admin_coach_user_id() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_default_column_config(p_coach_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_default_column_config(p_coach_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_default_column_config(p_coach_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_educational_videos_with_access() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_educational_videos_with_access() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_educational_videos_with_access() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_form_submission_phi(p_submission_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_form_submission_phi(p_submission_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_form_submission_phi(p_submission_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_assignable_clients() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_assignable_clients() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_my_assignable_clients() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_assigned_playlists() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_assigned_playlists() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_my_assigned_playlists() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_coach_profile() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_coach_profile() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_my_coach_profile() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_latest_form_submission_phi() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_latest_form_submission_phi() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_my_latest_form_submission_phi() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_phase_linked_content() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_phase_linked_content() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_my_phase_linked_content() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_profile_private() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_profile_private() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_my_profile_private() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_program_linked_content() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_program_linked_content() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_my_program_linked_content() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_roles() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_my_roles() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_my_roles() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_playlist_videos_with_access(p_playlist_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_playlist_videos_with_access(p_playlist_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_playlist_videos_with_access(p_playlist_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_required_content_summary() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_required_content_summary() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_required_content_summary() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_rls_audit_report() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_rls_audit_report() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_rls_audit_report() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_unread_message_count(p_client_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_unread_message_count(p_client_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_unread_message_count(p_client_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_unread_message_counts_for_staff() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_unread_message_counts_for_staff() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_unread_message_counts_for_staff() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_user_subroles(p_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_user_subroles(p_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_user_subroles(p_user_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_video_engagement_stats() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.get_video_engagement_stats() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_video_engagement_stats() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.has_active_care_team_access(p_staff_uid uuid, p_subscription_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.has_active_care_team_access(p_staff_uid uuid, p_subscription_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.has_active_care_team_access(p_staff_uid uuid, p_subscription_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.has_active_coach_relationship(p_coach_uid uuid, p_client_uid uuid, p_role text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.has_active_coach_relationship(p_coach_uid uuid, p_client_uid uuid, p_role text) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.has_active_coach_relationship(p_coach_uid uuid, p_client_uid uuid, p_role text) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.has_approved_subrole(p_user_id uuid, p_slug text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.has_approved_subrole(p_user_id uuid, p_slug text) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.has_approved_subrole(p_user_id uuid, p_slug text) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.is_admin_internal(_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.is_admin_internal(_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.is_admin_internal(_user_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.is_admin_or_coach_for_user(p_actor_uid uuid, p_client_uid uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.is_admin_or_coach_for_user(p_actor_uid uuid, p_client_uid uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.is_admin_or_coach_for_user(p_actor_uid uuid, p_client_uid uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.is_coach_for_client(client_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.is_coach_for_client(client_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.is_coach_for_client(client_user_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.is_coach_for_submission(submission_user_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.is_coach_for_submission(submission_user_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.is_coach_for_submission(submission_user_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.is_module_owner(p_user_id uuid, p_module_owner_coach_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.is_module_owner(p_user_id uuid, p_module_owner_coach_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.is_module_owner(p_user_id uuid, p_module_owner_coach_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.join_team(p_subscription_id uuid, p_team_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.join_team(p_subscription_id uuid, p_team_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.join_team(p_subscription_id uuid, p_team_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.list_active_coaches_for_service(p_service_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.list_active_coaches_for_service(p_service_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.list_active_coaches_for_service(p_service_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.list_active_teams_for_client() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.list_active_teams_for_client() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.list_active_teams_for_client() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.log_addon_session_atomic(p_purchase_id uuid, p_session_date date, p_notes text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.log_addon_session_atomic(p_purchase_id uuid, p_session_date date, p_notes text) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.log_addon_session_atomic(p_purchase_id uuid, p_session_date date, p_notes text) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.log_phi_access(p_actor_user_id uuid, p_target_user_id uuid, p_action text, p_resource_type text, p_resource_id uuid, p_fields_accessed text[], p_request_id text, p_ip_address text, p_user_agent text, p_metadata jsonb) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.log_phi_access(p_actor_user_id uuid, p_target_user_id uuid, p_action text, p_resource_type text, p_resource_id uuid, p_fields_accessed text[], p_request_id text, p_ip_address text, p_user_agent text, p_metadata jsonb) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.log_phi_access(p_actor_user_id uuid, p_target_user_id uuid, p_action text, p_resource_type text, p_resource_id uuid, p_fields_accessed text[], p_request_id text, p_ip_address text, p_user_agent text, p_metadata jsonb) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.mark_care_team_message_read(p_message_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.mark_care_team_message_read(p_message_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.mark_care_team_message_read(p_message_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.mark_care_team_thread_read(p_client_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.mark_care_team_thread_read(p_client_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.mark_care_team_thread_read(p_client_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.mark_coach_client_thread_read(p_client_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.mark_coach_client_thread_read(p_client_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.mark_coach_client_thread_read(p_client_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.mark_video_complete(p_video_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.mark_video_complete(p_video_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.mark_video_complete(p_video_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.refund_addon_purchase(p_purchase_id uuid, p_reason text, p_mode text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.refund_addon_purchase(p_purchase_id uuid, p_reason text, p_mode text) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.refund_addon_purchase(p_purchase_id uuid, p_reason text, p_mode text) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.reorder_macrocycle_blocks(p_macrocycle_id uuid, p_program_template_ids uuid[]) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.reorder_macrocycle_blocks(p_macrocycle_id uuid, p_program_template_ids uuid[]) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.reorder_macrocycle_blocks(p_macrocycle_id uuid, p_program_template_ids uuid[]) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.scan_phi_plaintext_violations() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.scan_phi_plaintext_violations() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.scan_phi_plaintext_violations() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.set_client_medical_clearance(p_client_user_id uuid, p_cleared boolean, p_summary text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.set_client_medical_clearance(p_client_user_id uuid, p_cleared boolean, p_summary text) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.set_client_medical_clearance(p_client_user_id uuid, p_cleared boolean, p_summary text) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.should_create_module_for_specialist(p_staff_user_id uuid, p_subscription_id uuid, p_day_date date) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.should_create_module_for_specialist(p_staff_user_id uuid, p_subscription_id uuid, p_day_date date) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.should_create_module_for_specialist(p_staff_user_id uuid, p_subscription_id uuid, p_day_date date) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.terminate_care_team_member(p_assignment_id uuid, p_reason_code care_team_end_reason, p_notes text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.terminate_care_team_member(p_assignment_id uuid, p_reason_code care_team_end_reason, p_notes text) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.terminate_care_team_member(p_assignment_id uuid, p_reason_code care_team_end_reason, p_notes text) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.update_my_profile_private(p_email text, p_full_name text, p_last_name text, p_phone text, p_date_of_birth date, p_gender text) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.update_my_profile_private(p_email text, p_full_name text, p_last_name text, p_phone text, p_date_of_birth date, p_gender text) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.update_my_profile_private(p_email text, p_full_name text, p_last_name text, p_phone text, p_date_of_birth date, p_gender text) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.verify_phi_view_isolation() FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.verify_phi_view_isolation() FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.verify_phi_view_isolation() TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.video_prerequisite_met(p_video_id uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.video_prerequisite_met(p_video_id uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.video_prerequisite_met(p_video_id uuid) TO authenticated, service_role';
  EXECUTE 'REVOKE ALL ON FUNCTION public.was_coach_during_record(p_client_id uuid, p_record_created_at timestamp with time zone, p_coach_id_at_creation uuid) FROM PUBLIC';
  EXECUTE 'REVOKE ALL ON FUNCTION public.was_coach_during_record(p_client_id uuid, p_record_created_at timestamp with time zone, p_coach_id_at_creation uuid) FROM anon';
  EXECUTE 'GRANT EXECUTE ON FUNCTION public.was_coach_during_record(p_client_id uuid, p_record_created_at timestamp with time zone, p_coach_id_at_creation uuid) TO authenticated, service_role';
END
$do$;
